db:
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: secret

hhvm:
    build: hhvm/.
    # image: brunoric/hhvm:deb
    volumes:
        - ./hhvm/logs:/var/log/hhvm
    expose:
        - "9000"
    volumes_from:
        - data
nginx:
    build: nginx/.
    volumes:
        - ./nginx/cache:/var/cache/nginx
        - ./nginx/logs:/var/log/nginx
    ports:
        - "8000:80"
    volumes_from:
        - data
    links:
        - hhvm

data:
  build: data/.
  volumes:
    - ./data/src:/var/www/src
  links:
      - db
